'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { Plus, Search } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { PageHeader } from '@/components/PageHeader';
import { CardListSkeleton, EmptyState, ErrorState } from '@/components/States';
import { useAuth } from '@/lib/auth/auth-context';
import {
  assignTicketForUser,
  createTicketForUser,
  loadAdminTicketsPageData,
  updateTicketStatusForUser,
} from '@/lib/features/tickets/ticket-center.data';
import {
  AdminTicketCard,
  AdminTicketComposerDialog,
  buildAdminStructuredDescription,
  getSuggestedIncidentTitle,
  IncidentCloseConfirmationDialog,
} from '@/lib/features/tickets/ticket-center.ui';
import { formatClientBadge } from '@/lib/presentation/labels';
import type { IncidentEntity } from '@/lib/types';

type PendingIncidentClose = {
  id: string;
  title: string;
  buildingName: string;
  unitLabel?: string | null;
  assigneeName?: string | null;
  currentStatus: IncidentEntity['status'];
};

export default function AdminTicketsPage() {
  const { user } = useAuth();
  const router = useRouter();
  const [allTickets, setAllTickets] = useState<IncidentEntity[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [buildingFilterId, setBuildingFilterId] = useState('');
  const [statusFilter, setStatusFilter] = useState<'ALL' | IncidentEntity['status']>('ALL');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [statusById, setStatusById] = useState<Record<string, IncidentEntity['status']>>({});
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [createBuildingId, setCreateBuildingId] = useState('');
  const [createUnitId, setCreateUnitId] = useState('');
  const [createProblemType, setCreateProblemType] = useState('');
  const [createWhereOccurs, setCreateWhereOccurs] = useState('');
  const [createLocationDetail, setCreateLocationDetail] = useState('');
  const [createSince, setCreateSince] = useState('');
  const [createImpact, setCreateImpact] = useState('');
  const [createTitle, setCreateTitle] = useState('');
  const [createAdditionalDetail, setCreateAdditionalDetail] = useState('');
  const [createPriority, setCreatePriority] = useState<IncidentEntity['priority']>('MEDIUM');
  const [titleWasAutoGenerated, setTitleWasAutoGenerated] = useState(false);
  const [buildings, setBuildings] = useState<{ id: string; name: string }[]>([]);
  const [units, setUnits] = useState<{ id: string; buildingId: string; number: string }[]>([]);
  const [staffByBuilding, setStaffByBuilding] = useState<Record<string, { id: string; buildingId: string; name: string; role: string }[]>>({});
  const [assigneeByTicket, setAssigneeByTicket] = useState<Record<string, string>>({});
  const [pendingClose, setPendingClose] = useState<PendingIncidentClose | null>(null);

  useEffect(() => {
    let isMounted = true;

    const load = async () => {
      if (!user) return;

      try {
        setIsLoading(true);
        setError(null);
        setActionError(null);
        const data = await loadAdminTicketsPageData(user);
        if (!isMounted) return;
        setAllTickets(data.tickets);
        setBuildings(data.buildings);
        setUnits(data.units);
        setStaffByBuilding(data.staffByBuilding);
        setCreateBuildingId((prev) => prev || data.defaultCreateBuildingId);
      } catch {
        if (!isMounted) return;
        setError('No pudimos cargar las incidencias.');
      } finally {
        if (!isMounted) return;
        setIsLoading(false);
      }
    };

    load();

    return () => {
      isMounted = false;
    };
  }, [user]);

  const reload = async () => {
    if (!user) return;
    setActionError(null);
    const data = await loadAdminTicketsPageData(user);
    setAllTickets(data.tickets);
    setBuildings(data.buildings);
    setUnits(data.units);
    setStaffByBuilding(data.staffByBuilding);
  };

  const tickets = useMemo(() => {
    const normalizedTerm = searchTerm.toLowerCase();
    return allTickets.filter((ticket) => {
      if (buildingFilterId && ticket.buildingId !== buildingFilterId) return false;
      if (statusFilter !== 'ALL' && ticket.status !== statusFilter) return false;
      return (
        ticket.title.toLowerCase().includes(normalizedTerm) ||
        ticket.description.toLowerCase().includes(normalizedTerm)
      );
    });
  }, [allTickets, buildingFilterId, searchTerm, statusFilter]);

  const buildingNameById = useMemo(
    () => new Map(buildings.map((building) => [building.id, building.name])),
    [buildings]
  );
  const unitNumberById = useMemo(() => new Map(units.map((unit) => [unit.id, unit.number])), [units]);

  const canCreate = user?.internalRole === 'BUILDING_ADMIN' || user?.internalRole === 'CLIENT_MANAGER';
  const canUpdate = user?.internalRole === 'BUILDING_ADMIN' || user?.internalRole === 'CLIENT_MANAGER';
  const allStatuses: IncidentEntity['status'][] = ['REPORTED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'];
  const ticketCounts = useMemo(
    () => ({
      total: allTickets.length,
      reported: allTickets.filter((ticket) => ticket.status === 'REPORTED').length,
      assigned: allTickets.filter((ticket) => ticket.status === 'ASSIGNED').length,
      inProgress: allTickets.filter((ticket) => ticket.status === 'IN_PROGRESS').length,
      resolved: allTickets.filter((ticket) => ticket.status === 'RESOLVED').length,
      closed: allTickets.filter((ticket) => ticket.status === 'CLOSED').length,
    }),
    [allTickets],
  );

  const maybeAutoSuggestTitle = (problemType: string, whereOccurs: string) => {
    if (createTitle !== '' && !titleWasAutoGenerated) return;
    const suggested = getSuggestedIncidentTitle(problemType, whereOccurs);
    if (!suggested) return;
    setCreateTitle(suggested);
    setTitleWasAutoGenerated(true);
  };

  const handleProblemTypeChange = (value: string) => {
    setCreateProblemType(value);
    maybeAutoSuggestTitle(value, createWhereOccurs);
  };

  const handleWhereOccursChange = (value: string) => {
    setCreateWhereOccurs(value);
    maybeAutoSuggestTitle(createProblemType, value);
  };

  const handleTitleChange = (value: string) => {
    setCreateTitle(value);
    const expectedAuto = getSuggestedIncidentTitle(createProblemType, createWhereOccurs);
    if (expectedAuto && value === expectedAuto) {
      setTitleWasAutoGenerated(true);
    } else {
      setTitleWasAutoGenerated(false);
    }
  };

  const resetCreateForm = () => {
    setCreateUnitId('');
    setCreateProblemType('');
    setCreateWhereOccurs('');
    setCreateLocationDetail('');
    setCreateSince('');
    setCreateImpact('');
    setCreateTitle('');
    setCreateAdditionalDetail('');
    setCreatePriority('MEDIUM');
    setTitleWasAutoGenerated(false);
  };

  const submitCreate = async () => {
    if (!user) return;

    const trimmedTitle = createTitle.trim();
    const trimmedLocationDetail = createLocationDetail.trim();
    const trimmedAdditionalDetail = createAdditionalDetail.trim();
    const needsDetail = createProblemType === 'Otro' || createWhereOccurs === 'Otro';

    if (!createBuildingId || !createProblemType || !createWhereOccurs || !createSince || !createImpact) {
      setActionError('Completa edificio, tipo de problema, ubicación, antigüedad y afectación.');
      return;
    }

    if (trimmedLocationDetail.length < 4) {
      setActionError('Indica el lugar específico del problema.');
      return;
    }

    if (!trimmedTitle || trimmedTitle.length < 6) {
      setActionError('El título debe tener al menos 6 caracteres.');
      return;
    }

    if (needsDetail && !trimmedAdditionalDetail) {
      setActionError('Agrega un detalle adicional cuando selecciones "Otro".');
      return;
    }

    const unit = createUnitId ? units.find((currentUnit) => currentUnit.id === createUnitId) : undefined;
    if (unit && unit.buildingId !== createBuildingId) {
      setActionError('La unidad seleccionada no pertenece al edificio.');
      return;
    }

    try {
      setIsSubmitting(true);
      setActionError(null);
      const buildingName = buildingNameById.get(createBuildingId) ?? createBuildingId;
      const unitLabel = unit ? `Depto ${unit.number}` : null;
      const structuredDescription = buildAdminStructuredDescription({
        buildingName,
        unitLabel,
        problemType: createProblemType,
        whereOccurs: createWhereOccurs,
        locationDetail: trimmedLocationDetail,
        since: createSince,
        impact: createImpact,
        additionalDetail: trimmedAdditionalDetail,
      });
      await createTicketForUser(user, {
        buildingId: createBuildingId,
        unitId: createUnitId || undefined,
        title: trimmedTitle,
        description: structuredDescription,
        priority: createPriority,
      });
      setIsCreateOpen(false);
      resetCreateForm();
      await reload();
      router.refresh();
    } catch {
      setActionError('No pudimos crear la incidencia.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const updateStatus = async (id: string) => {
    if (!user) return;
    const nextStatus = statusById[id];
    if (!nextStatus) return;

    try {
      setIsSubmitting(true);
      setActionError(null);
      await updateTicketStatusForUser(user, id, nextStatus);
      await reload();
      router.refresh();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'No pudimos actualizar la incidencia.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const closeIncident = async (id: string) => {
    if (!user) return;

    try {
      setIsSubmitting(true);
      setActionError(null);
      await updateTicketStatusForUser(user, id, 'CLOSED');
      await reload();
      router.refresh();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'No pudimos cerrar la incidencia.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const requestCloseIncident = (ticket: IncidentEntity) => {
    const buildingStaff = staffByBuilding[ticket.buildingId] ?? [];
    const currentAssignee = buildingStaff.find((staff) => staff.id === ticket.assignedToUserId);
    setActionError(null);
    setPendingClose({
      id: ticket.id,
      title: ticket.title,
      buildingName: buildingNameById.get(ticket.buildingId) ?? ticket.buildingId,
      unitLabel: ticket.unitId ? (unitNumberById.get(ticket.unitId) ?? ticket.unitId) : null,
      assigneeName: currentAssignee?.name ?? null,
      currentStatus: ticket.status,
    });
  };

  const confirmCloseIncident = async () => {
    if (!pendingClose) return;
    await closeIncident(pendingClose.id);
    setPendingClose(null);
  };

  const assignIncident = async (id: string) => {
    if (!user) return;
    const assignedToUserId = assigneeByTicket[id];
    if (!assignedToUserId) {
      setActionError('Selecciona un responsable antes de asignar la incidencia.');
      return;
    }

    try {
      setIsSubmitting(true);
      setActionError(null);
      await assignTicketForUser(user, id, assignedToUserId);
      setAssigneeByTicket((current) => {
        const next = { ...current };
        delete next[id];
        return next;
      });
      setStatusById((current) => {
        const next = { ...current };
        delete next[id];
        return next;
      });
      await reload();
      router.refresh();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'No pudimos asignar la incidencia.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const actions = (
    <>
      <select
        value={statusFilter}
        onChange={(event) => setStatusFilter(event.target.value as 'ALL' | IncidentEntity['status'])}
        className="px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-xl font-bold text-sm"
      >
        <option value="ALL">Todos los estados</option>
        <option value="REPORTED">Reportada</option>
        <option value="ASSIGNED">Asignada</option>
        <option value="IN_PROGRESS">En progreso</option>
        <option value="RESOLVED">Resuelta</option>
        <option value="CLOSED">Cerrada</option>
      </select>
      {canCreate && (
        <button
          onClick={() => {
            setActionError(null);
            setIsCreateOpen(true);
          }}
          className="flex items-center px-4 py-2 bg-primary text-white rounded-xl font-bold text-sm shadow-lg shadow-primary/20 hover:bg-primary/90 transition-all"
        >
          <Plus className="w-4 h-4 mr-2" /> Nueva incidencia
        </button>
      )}
    </>
  );

  return (
    <div className="flex flex-col h-full bg-slate-50/50">
      <PageHeader title="Incidencias" description="Gestiona solicitudes de mantenimiento y reportes operativos" actions={actions} />

      <div className="p-6 md:p-8 space-y-6">
        {formatClientBadge(user) && (
          <div className="max-w-2xl">
            <span className="px-3 py-1.5 rounded-full bg-slate-100 text-slate-600 text-[10px] font-black uppercase tracking-widest">
              {formatClientBadge(user)}
            </span>
          </div>
        )}

        {actionError && <ErrorState title="Accion no disponible" description={actionError} />}
        {!isLoading ? (
          <div className="flex flex-wrap gap-2">
            <span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-slate-600">
              Total {ticketCounts.total}
            </span>
            <span className="rounded-full bg-rose-50 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-rose-700">
              Reportadas {ticketCounts.reported}
            </span>
            <span className="rounded-full bg-amber-50 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-amber-700">
              Asignadas {ticketCounts.assigned + ticketCounts.inProgress}
            </span>
            <span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-emerald-700">
              Resueltas {ticketCounts.resolved}
            </span>
            <span className="rounded-full bg-slate-200 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-slate-700">
              Cerradas {ticketCounts.closed}
            </span>
          </div>
        ) : null}

        <div className="flex flex-col md:flex-row gap-4 max-w-4xl">
          <div className="relative group flex-1">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 group-focus-within:text-primary transition-colors" />
            <input
              type="text"
              value={searchTerm}
              onChange={(event) => setSearchTerm(event.target.value)}
              placeholder="Buscar por título o descripción..."
              className="w-full pl-12 pr-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-4 focus:ring-primary/5 focus:border-primary outline-none transition-all text-sm font-medium"
            />
          </div>
          <select
            value={buildingFilterId}
            onChange={(event) => setBuildingFilterId(event.target.value)}
            className="w-full md:w-72 px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-4 focus:ring-primary/5 focus:border-primary outline-none transition-all text-sm font-bold"
          >
            <option value="">Todos los edificios</option>
            {buildings.map((building) => (
              <option key={building.id} value={building.id}>
                {building.name}
              </option>
            ))}
          </select>
        </div>

        {error ? (
          <ErrorState title="Error" description={error} />
        ) : isLoading ? (
          <CardListSkeleton count={4} label="Cargando incidencias..." />
        ) : tickets.length === 0 ? (
          <EmptyState title="Sin incidencias" description={searchTerm ? `No hay resultados para "${searchTerm}".` : 'Aun no hay incidencias registradas.'} />
        ) : (
          <div className="space-y-3 max-w-4xl">
            {tickets.map((ticket) => (
              <AdminTicketCard
                key={ticket.id}
                ticket={ticket}
                buildingName={buildingNameById.get(ticket.buildingId) ?? ticket.buildingId}
                unitLabel={ticket.unitId ? (unitNumberById.get(ticket.unitId) ?? ticket.unitId) : null}
                canUpdate={Boolean(canUpdate)}
                isSubmitting={isSubmitting}
                selectedStatus={statusById[ticket.id] ?? ''}
                allStatuses={allStatuses}
                staffOptions={staffByBuilding[ticket.buildingId] ?? []}
                selectedAssignee={assigneeByTicket[ticket.id] ?? ticket.assignedToUserId ?? ''}
                onStatusChange={(status) => setStatusById((prev) => ({ ...prev, [ticket.id]: status }))}
                onSaveStatus={() => updateStatus(ticket.id)}
                onCloseIncident={() => requestCloseIncident(ticket)}
                onAssigneeChange={(userId) => setAssigneeByTicket((prev) => ({ ...prev, [ticket.id]: userId }))}
                onAssign={() => assignIncident(ticket.id)}
              />
            ))}
          </div>
        )}
      </div>

      <AdminTicketComposerDialog
        isOpen={isCreateOpen}
        isSubmitting={isSubmitting}
        buildings={buildings}
        units={units}
        buildingId={createBuildingId}
        unitId={createUnitId}
        problemType={createProblemType}
        whereOccurs={createWhereOccurs}
        locationDetail={createLocationDetail}
        since={createSince}
        impact={createImpact}
        title={createTitle}
        additionalDetail={createAdditionalDetail}
        priority={createPriority}
        error={actionError}
        onClose={() => setIsCreateOpen(false)}
        onBuildingChange={setCreateBuildingId}
        onUnitChange={setCreateUnitId}
        onProblemTypeChange={handleProblemTypeChange}
        onWhereOccursChange={handleWhereOccursChange}
        onLocationDetailChange={setCreateLocationDetail}
        onSinceChange={setCreateSince}
        onImpactChange={setCreateImpact}
        onTitleChange={handleTitleChange}
        onAdditionalDetailChange={setCreateAdditionalDetail}
        onPriorityChange={setCreatePriority}
        onSubmit={submitCreate}
      />

      <IncidentCloseConfirmationDialog
        isOpen={Boolean(pendingClose)}
        isSubmitting={isSubmitting}
        title={pendingClose?.title ?? ''}
        buildingName={pendingClose?.buildingName ?? ''}
        unitLabel={pendingClose?.unitLabel}
        assigneeName={pendingClose?.assigneeName}
        currentStatus={pendingClose?.currentStatus ?? 'REPORTED'}
        onClose={() => setPendingClose(null)}
        onConfirm={confirmCloseIncident}
      />
    </div>
  );
}
